### ISSUE TITLE
Warrior Execute button not being greyed out properly.

### ISSUE THREAD

**Issue by siven80** [tullamods/tullaRange#36]
The addon doesnt seem to grey out Execute correctly on Retail.
There has been many times it hasnt greyed out Execute while it is unable to be used. On a button with and without a keybind.
Havent even been able to understand why either.

**Comment by vyfvyf** [comment]
Can confirm, happens on my action bars that use Show States. Fury spec.
For example my bars use `[exists, nomounted][combat] show; hide`
When no target is present my bars are hidden, then i select NPC and Execute not greyed out properly on appeared bars. Range check works fine though.

**Comment by siven80** [comment]
Ah yes it seems thats it.
Had my bars (default UI) set to visible in combat. 
When turned off to show all the time, Execute seems to grey out properly.

**Comment by Tuller** [comment]
This should be resolved in 11.0.3

**Comment by vyfvyf** [comment]
Not fixed for me in 11.0.3, actually got worse.
Before 11.0.3 it was only on actionbars which use show states. Now in 11.0.3 after a while bug appears even on always active actionbars.

Steps to reproduce:
1. Enable Dominos bar with Show States `[exists, nomounted][combat] show; hide`
2. Place Execute on it (Fury spec)
3. Clear target
4. Walk out of range
5. Target enemy NPC (while out of range): **Execute icon is red**
6. Walk to NPC:  **Execute appears usable while its not**

**Comment by siven80** [comment]
Yeah, its still not working right.

Not greying out when it should.

**Comment by arcadepro** [comment]
Fixed in 11.04. Thanks Tuller.

**Comment by siven80** [comment]
Certainly seems to be fixed. thanks
